cmd_arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb := clang -E -Wp,-MMD,arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -x assembler-with-cpp -o arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.dts.tmp arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dts ; ./scripts/dtc/dtc -O dtb -o arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb -b 0 -a 4 -iarch/arm64/boot/dts/qcom/ -i./scripts/dtc/include-prefixes -Wno-interrupt_provider -@ -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-simple_bus_reg -Wno-unique_unit_address -Wno-pci_device_reg  -d arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.d.dtc.tmp arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.dts.tmp 2>arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb.dtout || ( cat  arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb.dtout; for err in "$$(cat  arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb.dtout | grep 'Error:')"; do echo "See more detail error as below:"; cat $$(echo $$err | cut -d':' -f2) | awk '{printf("ERROR: %6d  %s\n"), NR, $$0}' | head -n $$(echo $$err | grep -Eo ':[0-9]+' | cut -d':' -f2) | tail -n 2; done; rm  arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb.dtout; false; ) ; ./scripts/dtc/dtc -q -O dts -I dtb -o arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb.reverse.dts arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb ; cat arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.d.pre.tmp arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.d.dtc.tmp > arch/arm64/boot/dts/qcom/.sdm630-sony-xperia-nile-pioneer.dtb.d

source_arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb := arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dts

deps_arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb := \

arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb: $(deps_arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb)

$(deps_arch/arm64/boot/dts/qcom/sdm630-sony-xperia-nile-pioneer.dtb):
